labflow:
  security:
    oidc:
      enabled: true
      expected-issuer: ${OIDC_PUBLIC_ISSUER_URI:http://keycloak.localhost:8180/realms/labflow}
      mapping:
        borrowers: ${LABFLOW_OIDC_BORROWER_IDENTITIES:}
        managers: ${LABFLOW_OIDC_MANAGER_IDENTITIES:}
        technicians: ${LABFLOW_OIDC_TECHNICIAN_IDENTITIES:}
        lab-id: ${LABFLOW_OIDC_LAB_ID:FH_AACHEN}
        lab-name: ${LABFLOW_OIDC_LAB_NAME:Labor FH Aachen}

spring:
  security:
    oauth2:
      client:
        registration:
          labflow:
            provider: labflow
            client-id: ${OIDC_CLIENT_ID:labflow-web}
            client-secret: ${OIDC_CLIENT_SECRET:}
            client-authentication-method: ${OIDC_CLIENT_AUTHENTICATION_METHOD:none}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
            client-name: FH Aachen SSO
        provider:
          labflow:
            authorization-uri: ${OIDC_AUTHORIZATION_URI:http://keycloak.localhost:8180/realms/labflow/protocol/openid-connect/auth}
            token-uri: ${OIDC_TOKEN_URI:http://keycloak:8080/realms/labflow/protocol/openid-connect/token}
            jwk-set-uri: ${OIDC_JWK_SET_URI:http://keycloak:8080/realms/labflow/protocol/openid-connect/certs}
            user-info-uri: ${OIDC_USER_INFO_URI:http://keycloak:8080/realms/labflow/protocol/openid-connect/userinfo}
            user-name-attribute: sub
